### ISSUE TITLE
35c3 Lightning Talk "Write me an email" - aber Du gibst keine Email Adresse an 😡

### ISSUE THREAD

**Issue by mro** [dns2utf8/alpm-rs#10]
wohin soll man denn schreiben?

**Comment by mro** [comment]
den da: https://c3lt.de/35c3/talk/AAJ97M/

**Comment by dns2utf8** [comment]
Hallo @mro 

Danke für den Hinweis, kannst du mir an dns2utf8@estada.ch schreiben?

Grüsse

**Comment by dns2utf8** [comment]
Falls du lieber ein [Issue aufmachen](https://gitlab.com/dns2utf8/revfs/issues) möchtest ist das auch ein super Kommunikationskanal.
