### ISSUE TITLE
Crate ownership

### ISSUE THREAD

**Issue by Morganamilo** [dns2utf8/alpm-rs#11]
Hello, this project seems pretty dead. I've written my own alpm bindings and would like to push it to crates.io. There are already 3 different incomplete alpm crates (alpm libalpm libalpm-fork). Would you be willing to hand me the ownership of the crate so I can reuse the name?

**Comment by dns2utf8** [comment]
Hi

You appear to have a more complete project than me. 
I am currently on the road, so it would take me some time. 

I am interested in a working crate that either interfaces with pacman or (best case) can be used to replace the current c pacman.

The current crate is used in our hackerspace, so your versiion would have to start above.that.

Best, 
Stefan

**Comment by Morganamilo** [comment]
I just finished it last night so it does need more testing. I know there's some lifetime issues that I probably need to find. And I'll be tweaking it here and there for usability.

But it works, and my bindings actually implement every single ALPM function.

So hopefully it's suitable for your hackerspace.

**Comment by Morganamilo** [comment]
Any update here? Not sure what being on the road means exactly. Any estimate on when you'll be able to do this?

**Comment by ilpianista** [comment]
@Morganamilo I don't understand the problem here.

I mean, you cannot own all the existing published crates and even if you do, you will not be able to own any new alpm crate which will be published in the next weeks/months/years, so, why don't you just publish your version and make devs decide which one should be the "alpm crate" to be used?

My 2 cents.

**Comment by Morganamilo** [comment]
Where did I say I wanted to control all of the alpm crates that will ever be published? As I said, I simply want to re use an existing name, rather than add to the spam of `alpm`, `alpm.rs`, `libalpm` and `libalpm-fork`.

**Comment by dns2utf8** [comment]
I added you as an owner. I ask that you use a version =< 0.5.0

**Comment by Morganamilo** [comment]
Thanks, will do. Can't see myself as an owner though.

**Comment by dns2utf8** [comment]
You should have an invite in your mailbox.

**Comment by Morganamilo** [comment]
Ah right, found it. Thank you very much.
