### ISSUE TITLE
Is this really a reverse engineering project?

### ISSUE THREAD

**Issue by ghost** [dns2utf8/alpm-rs#8]
@dns2utf8
This doesnt look like a reverse engineering project as you are basically just using extern (probably C) functions from the library.
So this would be rather a wrapper.

**Comment by ghost** [comment]
I'd really appreciate a response.

**Comment by dns2utf8** [comment]
Hi @nifker 

Well it started as a wrapper, but turned a bit more complicated when I realized that it was not clear who should free the memory.
Currently the rust code simply does never free anything.

Back in the day when I created this code the intention was to go as far as possible to prove that at least parts of pacman could be written in rust.
Are you interested in that direction?

Cheers,
Stefan

**Comment by ghost** [comment]
@dns2utf8 I can see that, as this shouldn't be a problem anymore when using native Rust functions instead of the Symbols.
I would and can write for the beginning some functions and then try to make their behavior as similar to the original as possible and would then go on.

**Comment by dns2utf8** [comment]
That sounds great. Looking forward to it :+1:
